### ISSUE TITLE
Bug: app crashed on query feeds, when a random text is added on the feed and saved

### ISSUE THREAD

**Issue by darewealth** [zouroboros/podcast-watcher#15]
### Describe the bug.

The app crashed when a random text is added into the query feed and the filter is changed to feed, then saved. 

### Steps to reproduce.

* Launch the app

* Click on the menu

* Click add query and add any random text 

* Then click on add filter and change filter type to feed

* Then save

### Expected Behaviour
I expect to receive a message that the query is not supported or more other data and not a crash

### Screen recording
https://youtu.be/Pi-wKW7hri4

### Devices and Versions)

* Device: [itel]

* Version [6.1]

* App version [0.0.1

### Log.

```05-06 08:15:38.523 11420 11420 E AndroidRuntime: FATAL EXCEPTION: main
05-06 08:15:38.523 11420 11420 E AndroidRuntime: Process: me.murks.feedwatcher, PID: 11420
05-06 08:15:38.523 11420 11420 E AndroidRuntime: java.lang.IndexOutOfBoundsException
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at java.util.LinkedList.get(LinkedList.java:519)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at me.murks.feedwatcher.activities.FilterUiModel.filter(FilterUiModel.kt:27)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at me.murks.feedwatcher.activities.FilterRecyclerViewAdapter.filter(FilterRecyclerViewAdapter.kt:39)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at me.murks.feedwatcher.activities.QueryActivity.onOptionsItemSelected(QueryActivity.kt:110)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at android.app.Activity.onMenuItemSelected(Activity.java:2919)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:371)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:197)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at android.view.View.performClick(View.java:5209)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21166)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
05-06 08:15:38.523 11420 11420 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)```

**Comment by zouroboros** [comment]
Fixed by cb084db597a0cc2b9de00152bba11c50345989dc
